- name: make sure source directory exists for clones
  file:
    path: "{{ download_to }}"
    state: directory

- name: clone repository
  git:
    repo: "git://{{ uri }}"
    dest: "{{ src }}"
    version: "{{ version }}"

- name: build
  make:
    chdir: "{{ src }}"
    params:
      j: 4
  changed_when: false

- name: install
  make:
    chdir: "{{ src }}"
    target: install
  become: yes
  changed_when: false
