- name: make sure ~/src exists for clones
  file:
    path: ~/src
    state: directory
- name: remove any prior clone
  file:
    path: ~/src/st
    state: absent
- name: clone dwm repository
  git:
    repo: git://github.com/j-sv/st
    dest: ~/src/st
    update: yes
    force: yes
- name: checkout patches tag
  command: git checkout j-sv-0.8.2
  args:
    chdir: ~/src/st
- name: build
  make:
    chdir: ~/src/st
- name: install
  make:
    chdir: "{{ lookup('env', 'HOME') }}/src/st"
    target: install
  become: yes
