- name: remove any existing bashrc
  file:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    state: absent

- name: link bashrc
  file:
    src: "{{ role_path }}/files/bashrc"
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    state: link

- name: remove any existing bash_aliases
  file:
    path: "{{ lookup('env', 'HOME') }}/.bash_aliases"
    state: absent

- name: link aliases
  file:
    src: "{{ role_path }}/files/bash_aliases"
    path: "{{ lookup('env', 'HOME') }}/.bash_aliases"
    state: link

- name: create directory for completions
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/completions"
    state: directory

- name: generate completions for kubectl
  command: kubectl completion bash
  register: kubectl_completion
- name: write kubectl completion to file
  copy:
    content: "{{ kubectl_completion.stdout }}"
    dest: "{{ lookup('env', 'HOME') }}/.local/completions/helm.bash"
- name: generate completions for helm
  command: helm completion bash
  register: helm_completion 
- name: write helm completion to file
  copy:
    content: "{{ helm_completion.stdout }}"
    dest: "{{ lookup('env', 'HOME') }}/.local/completions/kubectl.bash"
