- name: create systemd user unit directory
  file:
    path: "{{ dest }}"
    state: directory

- name: link units
  file:
    src: "{{ src }}/{{ item }}"
    path: "{{ dest }}/{{ item }}"
    state: link
  with_items:
    - xsession.target
    - statusbar.service
    - redshift.service

- name: reload daemon
  systemd:
    scope: user
    daemon_reload: yes

- name: start services
  systemd:
    scope: user
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - statusbar
    - redshift
