- name: install prerequisites
  apt:
    name:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
    state: present
  become: yes

- name: make sure source directory exists for clones
  file:
    path: "{{ download_to }}"
    state: directory

- name: clone repository
  git:
    repo: "git://{{ uri }}"
    dest: "{{ src }}"
    version: "{{ version }}"

- name: build
  make:
    chdir: "{{ src }}"
    params:
      j: 4
  changed_when: false

- name: install
  make:
    chdir: "{{ src }}"
    target: install
  become: yes
  changed_when: false

- name: remove any previous kube_ps1 download
  file:
    path: "{{ kube_ps1_src }}"
    state: absent
  changed_when: false
- name: download and unpack kube_ps1
  unarchive:
    src: "{{ kube_ps1_uri }}"
    dest: "{{ download_to }}"
    remote_src: yes
    creates: "{{ kube_ps1_src }}"
  changed_when: false
- name: copy kube_ps1 script
  copy:
    src: "{{ kube_ps1_src }}/kube-ps1.sh"
    dest: "/usr/local/bin/kube-ps1.sh"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: yes
  changed_when: false

- name: install statusbar script
  copy:
    src: "{{ role_path }}/files/statusbar"
    dest: "/usr/local/bin/statusbar"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: yes
  changed_when: false
- name: install statusbar-fuzzy-time script
  copy:
    src: "{{ role_path }}/files/statusbar-fuzzy-time.sh"
    dest: "/usr/local/bin/statusbar-fuzzy-time.sh"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: yes
  changed_when: false
- name: install statusbar-fuzzy-day script
  copy:
    src: "{{ role_path }}/files/statusbar-fuzzy-day.sh"
    dest: "/usr/local/bin/statusbar-fuzzy-day.sh"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: yes
  changed_when: false
