- name: install prerequisites
  apt:
    name:
      - libxrandr-dev
    state: present
  become: yes

- name: make sure source directory exists for clones
  file:
    path: "{{ download_to }}"
    state: directory

- name: clone dwm repository
  git:
    repo: "git://{{ url }}"
    dest: "{{ src }}"
    version: "{{ version }}"

- name: build
  make:
    chdir: "{{ src }}"
  changed_when: false

- name: install
  make:
    chdir: "{{ src }}"
    target: install
  become: yes
  changed_when: false

- name: suid
  file:
    path: /usr/local/bin/slock
    mode: u+s
  become: yes
