- name: install dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - libncurses-dev
    - libpython3.6-dev
    - nodejs
    - yarn
  become: yes
- name: make sure src directory exists
  file:
    path: "{{ download_to }}"
    state: directory
- name: download and unpack
  unarchive:
    src: "{{ uri }}"
    dest: "{{ download_to }}"
    remote_src: yes
    creates: "{{ src }}"
- name: configure
  command: ./configure --enable-multibyte --enable-rubyinterp=yes --enable-python3interp=yes --with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu --with-tlib=ncurses
  args:
    chdir: "{{ src }}"
- name: build
  make:
    chdir: "{{ src }}"
    params:
      j: 4
- name: install
  make:
    chdir: "{{ src }}"
    target: install
  become: yes
- name: copy vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    path: "{{ lookup('env', 'HOME') }}/.vimrc"
    state: link
- name: create autoload directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.vim/autoload"
    state: directory
- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env', 'HOME') }}/.vim/autoload/plug.vim"
