- name: install dependencies
  apt:
    name:
      - pinentry-tty
    state: present
  become: yes

- name: make sure there's a config directory
  file:
    path: "{{ dest }}"
    state: directory
    mode: 0700

- name: link gpg agent config
  file:
    src: "{{ role_path }}/files/gpg-agent.conf"
    path: "{{ dest }}/gpg-agent.conf"
    state: link
