- name: clone repository
  git:
    repo: "git://{{ uri }}"
    dest: "{{ src }}"
    version: "{{ version }}"

- name: build
  make:
    chdir: "{{ src }}"
    params:
      j: 4
  changed_when: false

- name: install
  make:
    chdir: "{{ lookup('env', 'HOME') }}/src/dmenu"
    target: install
  become: yes
  changed_when: false
